basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is API for NEUOJ-NG
  license: {}
  title: NEUOJ-NG-backend API
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: just a ping test
      operationId: ping
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping
      tags:
      - basic
swagger: "2.0"
